# Generated by Django 5.2.7 on 2025-12-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('asin', models.CharField(max_length=50, null=True)),
                ('thumbnail', models.URLField(null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('rating', models.CharField(max_length=20, null=True)),
                ('reviews', models.CharField(max_length=20, null=True)),
                ('link', models.URLField(null=True)),
                ('screaped_at', models.DateTimeField(auto_now_add=True, verbose_name='Escrapeado el')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['screaped_at'],
            },
        ),
    ]
